# Generated by Django 5.2.3 on 2025-06-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_chat', '0002_remove_conversation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
